version: '3.5'

services:
  laravel_nginx:
    build:
      context: ./nginx
    container_name: laravel_nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../app:/var/www/html
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/conf.d/:/etc/nginx/conf.d/
      - ./nginx/config/includes/:/etc/nginx/includes/
    depends_on:
      - laravel_php
      - laravel_syslog
    networks:
      static-network:
        ipv4_address: 172.20.128.1

  laravel_php:
    build:
      context: ./php
    container_name: laravel_php
    ports:
      - "9000:9000"
    volumes:
      - ../app:/var/www/html
    environment:
      - XDEBUG_MODE=coverage
    tty: true
    depends_on:
      - laravel_syslog
    networks:
      static-network:
        ipv4_address: 172.20.128.2

  laravel_syslog:
    build:
      context: ./syslog
    container_name: laravel_syslog
    ports:
      - "601:601"
    volumes:
      - ../tmp/log:/var/www/html/tmp/log
      - ./syslog/config/conf.d/:/etc/syslog-ng/conf.d/
    environment:
      - SYSLOG_DRIVER=file
    networks:
      static-network:
        ipv4_address: 172.20.128.3

  laravel_mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: laravel_mysql
    ports:
      - '3306:3306'
    volumes:
      - laravel_db_data:/var/lib/mysql
    environment:
      - DB_DATABASE=lrvl
      - DB_USERNAME=lrvl_admin
      - DB_PASSWORD=!@QWasZX@
      - DB_ROOT_PASSWORD=!@QWasZX@
      - MYSQL_DATABASE=lrvl
      - MYSQL_USER=lrvl_admin
      - MYSQL_PASSWORD=!@QWasZX@
      - MYSQL_ROOT_PASSWORD=root!@QWasZX@
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    networks:
      static-network:
        ipv4_address: 172.20.128.4

  laravel_adminer:
    image: adminer:latest
    container_name: laravel_adminer
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: laravel_mysql
    depends_on:
      - laravel_mysql
    networks:
      static-network:
        ipv4_address: 172.20.128.5

networks:
  laravel_network:
    driver: bridge
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.28.5.0/24

volumes:
  laravel_db_data:
    driver: local

